name: uas_ppb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1  # versi terbaru
  path_provider: ^2.0.11  # untuk mengakses direktori penyimpanan perangkat
  shared_preferences: ^2.0.15
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
